services:
  backend:
    image: krcdocker2138/stock-sentiment-analyzer:backend-v15
    container_name: analyzer-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
        - ./backend/.env
    ports:
      - 8000:8000

  frontend:
    image: krcdocker2138/stock-sentiment-analyzer:frontend-v15
    pull_policy: never
    container_name: analyzer-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production_stage
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_started

